//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPST_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPST_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to connect to GMail in 10 seconds, please verify your internet connexion..
        /// </summary>
        public static string IDS_ERROR_UNABLE_TO_CONNECT {
            get {
                return ResourceManager.GetString("IDS_ERROR_UNABLE_TO_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accepted portals:.
        /// </summary>
        public static string IDS_MAIN_ACCEPTED_PORTAL_TITLE {
            get {
                return ResourceManager.GetString("IDS_MAIN_ACCEPTED_PORTAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string IDS_MAIN_ALL_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("IDS_MAIN_ALL_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mean response time:.
        /// </summary>
        public static string IDS_MAIN_MEAN_RESPONSE_DAYS_TITLE {
            get {
                return ResourceManager.GetString("IDS_MAIN_MEAN_RESPONSE_DAYS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameters.
        /// </summary>
        public static string IDS_MAIN_MENU_PARAMETERS {
            get {
                return ResourceManager.GetString("IDS_MAIN_MENU_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Queries.
        /// </summary>
        public static string IDS_MAIN_MENU_QUERIES {
            get {
                return ResourceManager.GetString("IDS_MAIN_MENU_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh Data.
        /// </summary>
        public static string IDS_MAIN_REFRESH_DATA {
            get {
                return ResourceManager.GetString("IDS_MAIN_REFRESH_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejected portals:.
        /// </summary>
        public static string IDS_MAIN_REJECTED_PORTAL_TITLE {
            get {
                return ResourceManager.GetString("IDS_MAIN_REJECTED_PORTAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IPST Windows.
        /// </summary>
        public static string IDS_MAIN_TITLE {
            get {
                return ResourceManager.GetString("IDS_MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accepted on:.
        /// </summary>
        public static string IDS_PORTAL_ACCEPTED_ON_TITLE {
            get {
                return ResourceManager.GetString("IDS_PORTAL_ACCEPTED_ON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Postal Address.
        /// </summary>
        public static string IDS_PORTAL_POSTAL_ADDRESS_TITLE {
            get {
                return ResourceManager.GetString("IDS_PORTAL_POSTAL_ADDRESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejected on:.
        /// </summary>
        public static string IDS_PORTAL_REJECTED_ON_TITLE {
            get {
                return ResourceManager.GetString("IDS_PORTAL_REJECTED_ON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejection Reason.
        /// </summary>
        public static string IDS_PORTAL_REJECTION_REASON_TITLE {
            get {
                return ResourceManager.GetString("IDS_PORTAL_REJECTION_REASON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Submitted on:.
        /// </summary>
        public static string IDS_PORTAL_SUBMITTED_ON_TITLE {
            get {
                return ResourceManager.GetString("IDS_PORTAL_SUBMITTED_ON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Portal Details.
        /// </summary>
        public static string IDS_PORTAL_TITLE {
            get {
                return ResourceManager.GetString("IDS_PORTAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waiting Days.
        /// </summary>
        public static string IDS_PORTAL_WAITING_DAYS_TITLE {
            get {
                return ResourceManager.GetString("IDS_PORTAL_WAITING_DAYS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appeal Succeeded.
        /// </summary>
        public static string IDS_PORTALS_CONTEXTMENU_APPEAL_SUCCEEDED {
            get {
                return ResourceManager.GetString("IDS_PORTALS_CONTEXTMENU_APPEAL_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appeal this submission.
        /// </summary>
        public static string IDS_PORTALS_CONTEXTMENU_APPEALSUBMISSION {
            get {
                return ResourceManager.GetString("IDS_PORTALS_CONTEXTMENU_APPEALSUBMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details.
        /// </summary>
        public static string IDS_PORTALS_CONTEXTMENU_DETAILS {
            get {
                return ResourceManager.GetString("IDS_PORTALS_CONTEXTMENU_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignore Submission.
        /// </summary>
        public static string IDS_PORTALS_CONTEXTMENU_IGNORE_SUBMISSION {
            get {
                return ResourceManager.GetString("IDS_PORTALS_CONTEXTMENU_IGNORE_SUBMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manual Accept.
        /// </summary>
        public static string IDS_PORTALS_CONTEXTMENU_MANUAL_ACCEPT {
            get {
                return ResourceManager.GetString("IDS_PORTALS_CONTEXTMENU_MANUAL_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameters.
        /// </summary>
        public static string IDS_PORTALS_MENU_PARAMETERS {
            get {
                return ResourceManager.GetString("IDS_PORTALS_MENU_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort....
        /// </summary>
        public static string IDS_PORTALS_MENU_PARAMETERS_SORT {
            get {
                return ResourceManager.GetString("IDS_PORTALS_MENU_PARAMETERS_SORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By Accepted date.
        /// </summary>
        public static string IDS_PORTALS_MENU_PARAMETERS_SORT_ACCEPTED_DATE {
            get {
                return ResourceManager.GetString("IDS_PORTALS_MENU_PARAMETERS_SORT_ACCEPTED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Desc.
        /// </summary>
        public static string IDS_PORTALS_MENU_PARAMETERS_SORT_DESC {
            get {
                return ResourceManager.GetString("IDS_PORTALS_MENU_PARAMETERS_SORT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By Rejected date.
        /// </summary>
        public static string IDS_PORTALS_MENU_PARAMETERS_SORT_REJECT_DATE {
            get {
                return ResourceManager.GetString("IDS_PORTALS_MENU_PARAMETERS_SORT_REJECT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By Sumission date.
        /// </summary>
        public static string IDS_PORTALS_MENU_PARAMETERS_SORT_SUBMISSION_DATE {
            get {
                return ResourceManager.GetString("IDS_PORTALS_MENU_PARAMETERS_SORT_SUBMISSION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string IDS_PORTALS_SEARCH_TITLE {
            get {
                return ResourceManager.GetString("IDS_PORTALS_SEARCH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Portal submission is duplicate.
        /// </summary>
        public static string IDS_REJECTION_REASON_DUPLICATE {
            get {
                return ResourceManager.GetString("IDS_REJECTION_REASON_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your submission doesn&apos;t meet portal criteria.
        /// </summary>
        public static string IDS_REJECTION_REASON_NOT_MEET_CRITERIA {
            get {
                return ResourceManager.GetString("IDS_REJECTION_REASON_NOT_MEET_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your portal submission is too close from another existing portal.
        /// </summary>
        public static string IDS_REJECTION_REASON_TOO_CLOSE {
            get {
                return ResourceManager.GetString("IDS_REJECTION_REASON_TOO_CLOSE", resourceCulture);
            }
        }
    }
}
